[project]
name = "aws-crag-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "chainlit>=2.11.1",
    "fastapi[standard]>=0.139.0",
    "langchain>=1.3.15",
    "langchain-classic>=1.0.8",
    "langchain-docling>=3.0.0",
    "langchain-groq>=1.1.3",
    "langchain-huggingface>=1.2.2",
    "langchain-postgres>=0.0.17",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.11",
    "slowapi>=0.1.10",
    "sqlalchemy>=2.0.52",
    "structlog>=26.1.0",
    "uuid6>=2025.0.1",
]

[dependency-groups]
dev = [
    "pre-commit",
    "ruff",
]
