"""create indexstatrecord table

Revision ID: fa90b64b2d42
Revises:
Create Date: 2026-09-17 19:06:49.745374

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa90b64b2d42"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "index_stat_records",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stop_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("num_added", sa.Integer(), nullable=True),
        sa.Column("num_updated", sa.Integer(), nullable=True),
        sa.Column("num_skipped", sa.Integer(), nullable=True),
        sa.Column("num_deleted", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_index_stat_records")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("index_stat_records")
    # ### end Alembic commands ###
